# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-12-09 07:01+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n"

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/admin.py:46
msgid "Personal info"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/admin.py:47
msgid "Permissions"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/admin.py:50
msgid "Important dates"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/admin.py:134
#, python-format
msgid "%(name)s object with primary key %(key)r does not exist."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/admin.py:144
msgid "Password changed successfully."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/admin.py:164
#, python-format
msgid "Change password: %s"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/apps.py:15
msgid "Authentication and Authorization"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/base_user.py:49
msgid "password"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/base_user.py:50
msgid "last login"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:41
msgid "No password set."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:46
msgid "Invalid password format or unknown hashing algorithm."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:88
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:335
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:408
msgid "The two password fields didn’t match."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:91
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:144
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:180
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:412
msgid "Password"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:97
msgid "Password confirmation"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:100
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:421
msgid "Enter the same password as before, for verification."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:146
msgid ""
"Raw passwords are not stored, so there is no way to see this user’s "
"password, but you can change the password using <a href=\"{}\">this form</a>."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:187
#, python-format
msgid ""
"Please enter a correct %(username)s and password. Note that both fields may "
"be case-sensitive."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:190
msgid "This account is inactive."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:253
msgid "Email"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:338
msgid "New password"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:344
msgid "New password confirmation"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:380
msgid "Your old password was entered incorrectly. Please enter it again."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:383
msgid "Old password"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/forms.py:418
msgid "Password (again)"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:265
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:339
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:435
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:495
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:526
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:562
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:598
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:636
msgid "algorithm"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:266
msgid "iterations"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:267
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:345
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:437
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:496
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:527
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:637
msgid "salt"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:268
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:346
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:497
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:528
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:563
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:599
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:638
msgid "hash"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:340
msgid "variety"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:341
msgid "version"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:342
msgid "memory cost"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:343
msgid "time cost"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:344
msgid "parallelism"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:436
msgid "work factor"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/hashers.py:438
msgid "checksum"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:56
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:107
msgid "name"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:60
msgid "content type"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:62
msgid "codename"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:67
msgid "permission"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:68
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:110
msgid "permissions"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:117
msgid "group"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:118
#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:241
msgid "groups"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:232
msgid "superuser status"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:235
msgid ""
"Designates that this user has all permissions without explicitly assigning "
"them."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:244
msgid ""
"The groups this user belongs to. A user will get all permissions granted to "
"each of their groups."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:252
msgid "user permissions"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:254
msgid "Specific permissions for this user."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:325
msgid "username"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:328
msgid "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:331
msgid "A user with that username already exists."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:334
msgid "first name"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:335
msgid "last name"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:336
msgid "email address"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:338
msgid "staff status"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:340
msgid "Designates whether the user can log into this admin site."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:343
msgid "active"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:346
msgid ""
"Designates whether this user should be treated as active. Unselect this "
"instead of deleting accounts."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:350
msgid "date joined"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:359
msgid "user"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/models.py:360
msgid "users"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:102
#, python-format
msgid ""
"This password is too short. It must contain at least %(min_length)d "
"character."
msgid_plural ""
"This password is too short. It must contain at least %(min_length)d "
"characters."
msgstr[0] ""
msgstr[1] ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:112
#, python-format
msgid "Your password must contain at least %(min_length)d character."
msgid_plural "Your password must contain at least %(min_length)d characters."
msgstr[0] ""
msgstr[1] ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:151
#, python-format
msgid "The password is too similar to the %(verbose_name)s."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:157
msgid "Your password can’t be too similar to your other personal information."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:183
msgid "This password is too common."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:188
msgid "Your password can’t be a commonly used password."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:198
msgid "This password is entirely numeric."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:203
msgid "Your password can’t be entirely numeric."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/templates/registration/password_reset_subject.txt:2
#, python-format
msgid "Password reset on %(site_name)s"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/validators.py:12
msgid ""
"Enter a valid username. This value may contain only English letters, "
"numbers, and @/./+/-/_ characters."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/validators.py:22
msgid ""
"Enter a valid username. This value may contain only letters, numbers, and "
"@/./+/-/_ characters."
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/views.py:160
msgid "Logged out"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/views.py:217
msgid "Password reset"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/views.py:244
msgid "Password reset sent"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/views.py:254
msgid "Enter new password"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/views.py:314
msgid "Password reset unsuccessful"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/views.py:322
msgid "Password reset complete"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/views.py:334
msgid "Password change"
msgstr ""

#: sgi_django_venv/lib/python3.8/site-packages/django/contrib/auth/views.py:357
msgid "Password change successful"
msgstr ""
